### ISSUE TITLE
Broken Link in How Bash got so popular

### ISSUE THREAD

**Issue by ecliptik** [hxxbit/hxxbit.github.io#1]
I enjoyed reading your [How Bash got so popular](https://github.com/hxxbit/hxxbit.github.io/blob/master/_posts/2016-07-10-bash.md) post, and noticed the link to "What killed Sun Microsystems" is broken, it should be:

- http://hxxbit.vinci.cloud/2016/07/08/whatkilledsun/

instead of

- http://hxxbit.vinci.cloud/2016/06/08/whatkilledsun/

Also, if you're interested in Unix and Computer history, I highly recommend the following if you haven't read them already,

- https://en.wikipedia.org/wiki/Hackers:_Heroes_of_the_Computer_Revolution
- https://www.amazon.com/Dealers-Lightning-Xerox-PARC-Computer/dp/0887309895
- https://en.wikipedia.org/wiki/Lions%27_Commentary_on_UNIX_6th_Edition,_with_Source_Code

**Comment by hxxbit** [comment]
Thanks for telling me about the issue - I realized I had put the wrong dates in, so I updated the articles and some links were broken. Also thanks for sending me the articles! I appreciate it! :)
